
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const SIGNUP_UNSUCCESSFUL = 'SIGNUP_UNSUCCESSFUL';

export const GET_OFFICE_SUCCESSFUL = 'GET_OFFICE_SUCCESSFUL';
export const GET_OFFICE_UNSUCCESSFUL = 'GET_OFFICE_UNSUCCESSFUL';
export const ADD_OFFICE_SUCCESSFUL = 'ADD_OFFICE_SUCCESSFUL';
export const ADD_OFFICE_UNSUCCESSFUL = 'ADD_OFFICE_UNSUCCESSFUL';
export const GET_AN_OFFICE_SUCCESSFUL = 'GET_AN_OFFICE_SUCCESSFUL';
export const GET_AN_OFFICE_UNSUCCESSFUL = 'GET_AN_OFFICE_UNSUCCESSFUL';
export const EDIT_OFFICE_SUCCESSFUL = 'EDIT_OFFICE_SUCCESSFUL';
export const EDIT_OFFICE_UNSUCCESSFUL = 'EDIT_OFFICE_UNSUCCESSFUL';
export const DELETE_OFFICE_SUCCESSFUL = 'DELETE_OFFICE_SUCCESSFUL';
export const DELETE_OFFICE_UNSUCCESSFUL = 'DELETE_OFFICE_UNSUCCESSFUL';

export const GET_PARTY_SUCCESSFUL = 'GET_PARTY_SUCCESSFUL';
export const GET_PARTY_UNSUCCESSFUL = 'GET_PARTY_UNSUCCESSFUL';
export const ADD_PARTY_SUCCESSFUL = 'ADD_PARTY_SUCCESSFUL';
export const ADD_PARTY_UNSUCCESSFUL = 'ADD_PARTY_UNSUCCESSFUL';
export const GET_A_PARTY_SUCCESSFUL = 'GET_A_PARTY_SUCCESSFUL';
export const GET_A_PARTY_UNSUCCESSFUL = 'GET_A_PARTY_UNSUCCESSFUL';
export const EDIT_PARTY_SUCCESSFUL = 'EDIT_PARTY_SUCCESSFUL';
export const EDIT_PARTY_UNSUCCESSFUL = 'EDIT_PARTY_UNSUCCESSFUL';
export const DELETE_PARTY_SUCCESSFUL = 'DELETE_PARTY_SUCCESSFUL';
export const DELETE_PARTY_UNSUCCESSFUL = 'DELETE_PARTY_UNSUCCESSFUL';


export const GET_CANDIDATE_SUCCESSFUL = 'GET_CANDIDATE_SUCCESSFUL';
export const GET_CANDIDATE_UNSUCCESSFUL = 'GET_CANDIDATE_UNSUCCESSFUL';
export const ADD_CANDIDATE_SUCCESSFUL = 'ADD_CANDIDATE_SUCCESSFUL';
export const ADD_CANDIDATE_UNSUCCESSFUL = 'ADD_CANDIDATE_UNSUCCESSFUL';
export const GET_A_CANDIDATE_SUCCESSFUL = 'GET_A_CANDIDATE_SUCCESSFUL';
export const GET_A_CANDIDATE_UNSUCCESSFUL = 'GET_A_CANDIDATE_UNSUCCESSFUL';
export const EDIT_CANDIDATE_SUCCESSFUL = 'EDIT_CANDIDATE_SUCCESSFUL';
export const EDIT_CANDIDATE_UNSUCCESSFUL = 'EDIT_CANDIDATE_UNSUCCESSFUL';
export const DELETE_CANDIDATE_SUCCESSFUL = 'DELETE_CANDIDATE_SUCCESSFUL';
export const DELETE_CANDIDATE_UNSUCCESSFUL = 'DELETE_CANDIDATE_UNSUCCESSFUL';

export const CLEAR_STATE = 'CLEAR_STATE';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';